#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : minicom
Version  : 2.7.1
Release  : 2
URL      : https://fossies.org/linux/misc/minicom-2.7.1.tar.gz
Source0  : https://fossies.org/linux/misc/minicom-2.7.1.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : GPL-2.0
Requires: minicom-bin
Requires: minicom-license
Requires: minicom-locales
Requires: minicom-man
BuildRequires : ncurses-dev

%description
Minicom is a communications program that resembles the MSDOS Telix
somewhat. It has a dialing directory, color, full ANSI and VT100
emulation, an (external) scripting language and more.

Run 'minicom -s' as root to create a system wide configuration.
Users need read/write permissions on the serial port devices in
order to use minicom.

It's recommended to install lrzsz if you want to transfer files
with minicom.

%package bin
Summary: bin components for the minicom package.
Group: Binaries
Requires: minicom-license
Requires: minicom-man

%description bin
bin components for the minicom package.


%package license
Summary: license components for the minicom package.
Group: Default

%description license
license components for the minicom package.


%package locales
Summary: locales components for the minicom package.
Group: Default

%description locales
locales components for the minicom package.


%package man
Summary: man components for the minicom package.
Group: Default

%description man
man components for the minicom package.


%prep
%setup -q -n minicom-2.7.1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1531937276
%configure --disable-static
make  %{?_smp_mflags}

%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make VERBOSE=1 V=1 %{?_smp_mflags} check

%install
export SOURCE_DATE_EPOCH=1531937276
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/doc/minicom
cp COPYING %{buildroot}/usr/share/doc/minicom/COPYING
%make_install
%find_lang minicom

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/ascii-xfr
/usr/bin/minicom
/usr/bin/runscript
/usr/bin/xminicom

%files license
%defattr(-,root,root,-)
/usr/share/doc/minicom/COPYING

%files man
%defattr(-,root,root,-)
/usr/share/man/man1/ascii-xfr.1
/usr/share/man/man1/minicom.1
/usr/share/man/man1/runscript.1
/usr/share/man/man1/xminicom.1

%files locales -f minicom.lang
%defattr(-,root,root,-)

